const permissions = {
  // Admin related permissions
  ADD_ADMIN: "ADD_ADMIN",
  UPDATE_ADMIN: "UPDATE_ADMIN",
  DELETE_ADMIN: "DELETE_ADMIN",
  FETCH_ADMINS: "FETCH_ADMINS",
  LOGOUT_ADMIN_OR_EMPLOYEE: "LOGOUT_ADMIN_OR_EMPLOYEE",
  SEARCH_ADMIN_OR_EMPLOYEE: "SEARCH_ADMIN_OR_EMPLOYEE",

  // Category related permissions
  ADD_CATEGORY: "ADD_CATEGORY",
  UPDATE_CATEGORY_BY_ID: "UPDATE_CATEGORY_BY_ID",
  DELETE_CATEGORY: "DELETE_CATEGORY",
  FETCH_CATEGORY: "FETCH_CATEGORY",
  FETCH_CATEGORIES: "FETCH_CATEGORIES",
  FETCH_CATEGORY_BY_NAME: "FETCH_CATEGORY_BY_NAME",
  SEARCH_CATEGORIES: "SEARCH_CATEGORIES",

  // Display related permissions
  // curruntly we are not using this but in future we may add this feature
  // ADD_DISPLAY: "ADD_DISPLAY",
  // FETCH_DISPLAY: "FETCH_DISPLAY",
  // DELETE_DISPLAY: "DELETE_DISPLAY",

  // Order related permissions
  FETCH_ORDERS: "FETCH_ORDERS",
  SEARCH_ORDERS: "SEARCH_ORDERS",
  FETCH_ORDER_BY_ID: "FETCH_ORDER_BY_ID",
  UPDATE_ORDER_STATUS: "UPDATE_ORDER_STATUS",
  FETCH_TODAYS_ORDERS: "FETCH_TODAYS_ORDERS",
  DELETE_ORDER: "DELETE_ORDER",

  // Product related permissions
  FETCH_PRODUCTS: "FETCH_PRODUCTS",
  SEARCH_PRODUCTS: "SEARCH_PRODUCTS",
  ADD_PRODUCT: "ADD_PRODUCT",
  UPDATE_PRODUCT: "UPDATE_PRODUCT",
  DELETE_PRODUCT: "DELETE_PRODUCT",

  // Review related permissions
  FETCH_REVIEWS: "FETCH_REVIEWS",
  ADD_REVIEWS: "ADD_REVIEWS",
  DELETE_REVIEW: "DELETE_REVIEW",

  // User related permissions
  FETCH_USERS: "FETCH_USERS",
  SEARCH_USERS: "SEARCH_USERS",
  DELETE_USER: "DELETE_USER",
};

module.exports = permissions;
